package:
    name:           yii2-asset-paulzi-form
    namespace:      hiqdev\assets\paulziform
    title:          Yii2 asset for PaulZi Form JS library
    type:           yii2-extension
    keywords:       paulzi-form, asset, extension, yii2
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
